<a href="https://colab.research.google.com/github/tabaraei/CheatSheet/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## Numpy Arrays
1- Creating a Numpy array:

In [ ]:
A = np.array([1,2,3])
# array([1, 2, 3])

A = np.array([[1,2], [3,4]])
# array([[1, 2],
#        [3, 4]])

In [ ]:
A = np.arange(6)
# array([0, 1, 2, 3, 4, 5])

A = np.arange(4,19,3)
# array([ 4,  7, 10, 13, 16])

A = np.arange(9).reshape(3,3)
# array([[0, 1, 2],
#        [3, 4, 5],
#        [6, 7, 8]])

A = A.reshape((9,))
# array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
A = np.empty((2,1))
# array([[4.65502146e-310],
#        [1.48219694e-323]])

A = np.zeros((2,2))
# array([[0., 0.],
#        [0., 0.]])

A = np.ones((3,2))
# array([[1., 1.],
#        [1., 1.],
#        [1., 1.]])

A = np.full((2,3), 9)
# array([[9, 9, 9],
#        [9, 9, 9]])

A = np.eye(3)
# array([[1., 0., 0.],
#        [0., 1., 0.],
#        [0., 0., 1.]])

A = np.linspace(-4,4,5) # also check (num, endpoint) parameters
# array([-4., -2.,  0.,  2.,  4.])

# Create a Numpy array based on another array dimensions
A = np.empty_like(A)
A = np.zeros_like(A)
A = np.ones_like(A)
A = np.full_like(A,2)

2- Accessing Numpy arrays:

In [ ]:
A = np.arange(9).reshape(3,3)

print(A)
print('Get Element', A[1,2])
print('Get Row:', A[0])
print('Get Column', A[:,1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Get Element 5
Get Row: [0 1 2]
Get Column [1 4 7]


3- Operations on Numpy arrays:

In [ ]:
A = np.array([[1,2], 
              [5,3]])
B = np.array([[4,2], 
              [1,3]])

C = A + B
# array([[5, 4],
      #  [6, 6]])

C = A - B
# array([[-3,  0],
#        [ 4,  0]])

C = A * B
# array([[4, 4],
#        [5, 9]])

C = A / B
# array([[0.25, 1.  ],
#        [5.  , 1.  ]])

C = A ** B
# array([[ 1,  4],
#        [ 5, 27]])

C = 2*A - B + 5
# array([[ 3,  7],
#        [14,  8]])

C = A @ B
# array([[ 6,  8],
#        [23, 19]])

C = A.T
# array([[1, 5],
#        [2, 3]])

array([[1, 5],
       [2, 3]])

4- Shape of Numpy arrays:

In [1]:
A = np.ones(3)
print('Taking the transpose of a 1D array has NO effect')
print(A)
print(A.shape)
print(A.T)
print(A.T.shape)

print('But it does work if you have a 2D array of shape (3,1)')
A = np.ones((3,1)) # A = np.ones(3).reshape(-1,1)
print(A)
print(A.shape)
print(A.T)
print(A.T.shape)

Taking the transpose of a 1D array has NO effect
[1. 1. 1.]
(3,)
[1. 1. 1.]
(3,)
But it does work if you have a 2D array of shape (3,1)
[[1.]
 [1.]
 [1.]]
(3, 1)
[[1. 1. 1.]]
(1, 3)


In [ ]:
%time 2+2
help(np.array)

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 9.54 µs


4

In [ ]:
# SHOULD ORGANIZE LATER

reshape
flatten

array = [[1,2],[3,4]] 
print(np.linalg.det(array))

f = np.array([1,2])
g = np.array([4,5])
print(np.dot(f,g))

h = [[1,2],[3,4]] 
i = [[5,6],[7,8]]
print(np.matmul(h, i))

array = np.array( [1,2,3,4] )
print(np.min(array))
print(np.max(array))
print(np.mean(array))
print(np.median(array))
print(np.std(array))

f = np.array([1,2,3])
g = np.array([4,5,6])
print(np.hstack((f, g)))
print()
print(np.vstack((f, g)))

array = np.array([[1, 2, 3], [4, 5, 6]])
array[1]=2
print(array)

random_array = np.random.random((2,3))
print(random_array)